name: SurvivalAddons2
version: '${project.version}'
main: mc.analyzers.survivaladdons2.SurvivalAddons2
api-version: 1.18
authors: [ Analyzers, Laurent ]
description: SurvivalAddons v2
commands:
  getItem:
    description: Admin give
    usage: /getItem <Item>
    permission: SurvivalAddons2.getItem
    permission-message: Lacking SuvivalAddons2.getItem permission.
  getDust:
    description: Admin dust give
    usage: /getDust <Number of dust>
    permission: SurvivalAddons2.getDust
    permission-message: Lacking SurvivalAddons2.getDust permission.
  dust:
    description: Check dust
    usage: /dust
    aliases: [bal, money]
  checkItem:
    description: Check item
    usage: /checkItem
  withdraw:
    description: Withdraw dust
    usage: /withdraw [dust]
    aliases: [tr, wd]
  deposit:
    description: Deposits all dust
    usage: /deposit
    aliases: [dep]
  updateInventory:
    description: updates inventory.
  rename:
    description: renames item.
  setLives:
    description: sets lives.
  view:
    description: Views a player.
  setEffect:
    description: sets custom effect.
  quests:
    description: check quests.
  shop:
    description: opens shop.